(define (problem retail_problem)
  (:domain retail-recommendation)
  (:objects
    customer1 - customer
    classic_chino stretch_denim formal_slim premium_wool designer_linen relaxed_cargo soldout_travel - product
  )
  (:init
    (available classic_chino)
    (available designer_linen)
    (available formal_slim)
    (available premium_wool)
    (available relaxed_cargo)
    (available stretch_denim)
    (budget-sensitive customer1)
    (comfort-priority customer1)
    (customer customer1)
    (low-pressure customer1)
    (near-budget classic_chino customer1)
    (near-budget formal_slim customer1)
    (near-budget relaxed_cargo customer1)
    (near-budget soldout_travel customer1)
    (near-budget stretch_denim customer1)
    (premium-item designer_linen)
    (premium-item premium_wool)
    (product classic_chino)
    (product designer_linen)
    (product formal_slim)
    (product premium_wool)
    (product relaxed_cargo)
    (product soldout_travel)
    (product stretch_denim)
    (trousers classic_chino)
    (trousers designer_linen)
    (trousers formal_slim)
    (trousers premium_wool)
    (trousers relaxed_cargo)
    (trousers soldout_travel)
    (trousers stretch_denim)
    (under-budget classic_chino customer1)
    (under-budget formal_slim customer1)
    (under-budget relaxed_cargo customer1)
    (under-budget soldout_travel customer1)
    (under-budget stretch_denim customer1)
  )
  (:goal (and
      (alternative-offered customer1)
      (recommendation-made customer1)
  ))
)
